import { productsApi } from "../core/api.js";
import { startShell } from "./shell.js";
const money = value => `Rs. ${Number(value || 0).toLocaleString()}`;
const clean = value => String(value || "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const badge = status => `<span class="badge ${(status || "Draft").toLowerCase()}">${clean(status || "Draft")}</span>`;
async function init() {
  if (!await startShell("products", `<div class="page-head"><div><h2>Products</h2><p>Manage your online store catalogue.</p></div><a class="btn primary" href="product.html">+ Add product</a></div><div class="card"><div class="toolbar"><input class="search" id="search" placeholder="Search product, SKU, category…"><span id="count"></span></div><div style="overflow:auto"><table><thead><tr><th>Product</th><th>Status</th><th>Inventory</th><th>Price</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></div>`)) return;
  let products = await productsApi.list(); const rows = document.getElementById("rows"), count = document.getElementById("count");
  function render(query = "") { const visible = products.filter(product => [product.name,product.sku,product.category,product.brand].join(" ").toLowerCase().includes(query.toLowerCase())); count.textContent = `${visible.length} product${visible.length === 1 ? "" : "s"}`; rows.innerHTML = visible.length ? visible.map(product => `<tr><td><div class="product-name"><img class="thumb" src="${product.images?.[0] || "../images/placeholders/no-image.png"}" onerror="this.style.visibility='hidden'"><span>${clean(product.name)}<small style="display:block;color:#687385;font-weight:400">${clean(product.sku || "No SKU")} · ${clean(product.category || "Uncategorised")}</small></span></div></td><td>${badge(product.status)}</td><td>${Number(product.stock || 0)} in stock</td><td>${money(product.salePrice || product.price)}${product.salePrice ? `<small style="display:block;color:#687385;text-decoration:line-through">${money(product.price)}</small>` : ""}</td><td><div class="actions"><button data-edit="${product.id}">Edit</button><button data-delete="${product.id}">Delete</button></div></td></tr>`).join("") : `<tr><td colspan="5" class="empty">No products found. Add your first product to get started.</td></tr>`; document.querySelectorAll("[data-edit]").forEach(button => button.onclick = () => location.href = `product.html?id=${button.dataset.edit}`); document.querySelectorAll("[data-delete]").forEach(button => button.onclick = async () => { if (confirm("Delete this product?")) { await productsApi.delete(button.dataset.delete); products = await productsApi.list(); render(document.getElementById("search").value); } }); }
  document.getElementById("search").oninput = event => render(event.target.value); render();
}
init().catch(error => alert(error.message));
